import type { Metadata } from "next";
import NavBar from "@/components/NavBar";

import "./globals.css";
import { Footer } from "@/components/Footer";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <>
          <header className="absolute inset-x-0 top-0 z-50">
            <NavBar />
          </header>
          <main className="grow gap-2">{children}</main>
          <footer
            className="border-t py-3 text-center text-xs"
            style={{ background: "#005375" }}
          >
            <Footer />
          </footer>
          <div className="fixed bottom-4 right-4 flex flex-col">
            <button
              className="  text-white font-bold p-2 rounded-full shadow-lg"
              style={{
                padding: "12px",
                background: "#FFFFFFCC",
              }}
            >
              <Image
                src="/whatsapp_floating.svg"
                alt="whatsapp_floating"
                width={33}
                height={33}
              />
            </button>
            <button
              className="  text-white font-bold rounded-full shadow-lg"
              style={{
                background: "#FFFFFFCC",
                padding: "12px",
                marginTop: "5px",
              }}
            >
              <Image
                src="/floating_up.svg"
                alt="floating_up"
                width={27}
                height={27}
                className="m-auto"
              />
            </button>
          </div>
        </>
      </body>
    </html>
  );
}
