import type { Metadata } from "next";
import NavBar from "@/components/NavBar";

import "./globals.css";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <>
          <header className="absolute inset-x-0 top-0 z-50">
            <NavBar />
          </header>
          <main className="grow gap-2">{children}</main>
          <footer
            className="border-t py-3 text-center text-xs"
            style={{ background: "#005375" }}
          >
            <Footer />
          </footer>
        </>
      </body>
    </html>
  );
}
